public class PGP2Class {
	
	String fname;
	String lname;
	public void setFname(String fname)
        {
            this.fname = fname;
        }
        public void setLname(String lname)
        {
            this.lname = this.lname;
        }
        public String getFname()
        {
            return this.fname;
        }
        public String getLname()
        {
            return this.lname;
        }
}